// Catalogo interpretable de reglas CRH Assist V2.
// Esta capa queda preparada para persistirse luego en PostgreSQL
// y administrarse desde backend/API sin cambiar el contrato del frontend.

export const crhAssistRuleCatalog = [
  {
    id: 'follow-up-gap',
    name: 'Paciente sin control reciente',
    description: 'Detecta pacientes con brecha relevante desde su ultimo control clinico.',
    category: 'clinical',
    appliesTo: ['patient', 'history'],
    condition: { metric: 'daysSinceLastControl', operator: '>', threshold: 30 },
    weight: 14,
    severity: 'alta',
    enabled: true,
    relatedModule: 'historia-clinica',
    recommendedAction: 'Programar control prioritario y verificar continuidad asistencial.',
  },
  {
    id: 'high-cost-medication',
    name: 'Medicamento de alto costo',
    description: 'Identifica terapias con alto impacto farmacoeconomico sobre el caso.',
    category: 'medication',
    appliesTo: ['patient', 'medications'],
    condition: { metric: 'hasHighCostMedication', operator: '==', threshold: true },
    weight: 12,
    severity: 'alta',
    enabled: true,
    relatedModule: 'medicamentos',
    recommendedAction: 'Correlacionar respuesta clinica, continuidad terapeutica e impacto contractual.',
  },
  {
    id: 'above-expected-consumption',
    name: 'Consumo superior al esperado',
    description: 'Dispara alerta cuando el costo mensual supera el umbral esperado del caso.',
    category: 'financial',
    appliesTo: ['patient', 'contract', 'consumptions'],
    condition: { metric: 'consumptionVarianceRatio', operator: '>', threshold: 1 },
    weight: 15,
    severity: 'alta',
    enabled: true,
    relatedModule: 'contratos-pgp',
    recommendedAction: 'Revisar drivers clinicos y oportunidades de intervencion temprana.',
  },
  {
    id: 'pgp-margin-at-risk',
    name: 'Contrato PGP con margen en riesgo',
    description: 'Marca los casos donde el contrato asociado muestra presion de margen o desvio de consumo.',
    category: 'pgp',
    appliesTo: ['patient', 'contract'],
    condition: { metric: 'pgpMarginAtRisk', operator: '==', threshold: true },
    weight: 18,
    severity: 'critica',
    enabled: true,
    relatedModule: 'contratos-pgp',
    recommendedAction: 'Escalar el caso a seguimiento clinico-financiero y ajustar plan de contencion segura.',
  },
  {
    id: 'chronic-non-adherence',
    name: 'Paciente cronico sin adherencia',
    description: 'Se activa cuando hay señales de ruptura entre plan de manejo y continuidad terapeutica.',
    category: 'adherence',
    appliesTo: ['patient', 'history', 'medications'],
    condition: { metric: 'hasAdherenceRisk', operator: '==', threshold: true },
    weight: 12,
    severity: 'alta',
    enabled: true,
    relatedModule: 'pacientes',
    recommendedAction: 'Activar seguimiento de adherencia, educacion y contacto de soporte.',
  },
  {
    id: 'high-risk-diagnosis',
    name: 'Diagnostico de alto riesgo',
    description: 'Detecta diagnosticos de alta complejidad o con elevada probabilidad de descompensacion.',
    category: 'clinical',
    appliesTo: ['patient', 'diagnoses'],
    condition: { metric: 'hasHighRiskDiagnosis', operator: '==', threshold: true },
    weight: 13,
    severity: 'alta',
    enabled: true,
    relatedModule: 'historia-clinica',
    recommendedAction: 'Mantener control estrecho y trazabilidad de resultados clinicos.',
  },
  {
    id: 'incomplete-history',
    name: 'Historia clinica incompleta',
    description: 'Detecta brechas documentales que limitan la interpretacion clinica y financiera.',
    category: 'history',
    appliesTo: ['history'],
    condition: { metric: 'historyCompletenessRatio', operator: '<', threshold: 0.75 },
    weight: 10,
    severity: 'media',
    enabled: true,
    relatedModule: 'historia-clinica',
    recommendedAction: 'Completar anamnesis, plan de manejo y ordenes pendientes antes del siguiente cierre.',
  },
  {
    id: 'deficit-patient',
    name: 'Paciente deficitario',
    description: 'Marca casos con alta presion acumulada sobre el margen contractual.',
    category: 'financial',
    appliesTo: ['patient', 'contract', 'consumptions'],
    condition: { metric: 'isDeficitPatient', operator: '==', threshold: true },
    weight: 14,
    severity: 'alta',
    enabled: true,
    relatedModule: 'contratos-pgp',
    recommendedAction: 'Realizar junta clinico-financiera del caso y definir plan de contencion segura.',
  },
  {
    id: 'profitable-patient',
    name: 'Paciente rentable',
    description: 'Reconoce casos con control adecuado y comportamiento economico favorable.',
    category: 'financial',
    appliesTo: ['patient', 'contract', 'consumptions'],
    condition: { metric: 'isProfitablePatient', operator: '==', threshold: true },
    weight: -8,
    severity: 'baja',
    enabled: true,
    relatedModule: 'pacientes',
    recommendedAction: 'Mantener seguimiento estandar y reforzar continuidad del plan actual.',
  },
  {
    id: 'avoidable-event',
    name: 'Posible evento evitable',
    description: 'Advierte cuando una brecha operacional o clinica podria terminar en consumo prevenible.',
    category: 'operational',
    appliesTo: ['patient', 'consumptions', 'history'],
    condition: { metric: 'hasPotentialAvoidableEvent', operator: '==', threshold: true },
    weight: 12,
    severity: 'alta',
    enabled: true,
    relatedModule: 'dashboard',
    recommendedAction: 'Intervenir antes del siguiente ciclo de consumo o agudizacion esperada.',
  },
]

