export const patients = [
  {
    id: 'pac-001',
    tipoDocumento: 'CC',
    numeroDocumento: '1112458796',
    nombres: 'Laura',
    apellidos: 'Burbano',
    edad: 38,
    sexo: 'F',
    ciudad: 'Pasto',
    eps: 'Nueva EPS',
    sede: 'Pasto',
    diagnostico: 'M06.9 Artritis reumatoide seropositiva',
    estado: 'Activo',
    contratoId: 'ctr-001',
    programa: 'Pacientes cronicos',
    costoAcumulado: '$18,6 M',
  },
  {
    id: 'pac-002',
    tipoDocumento: 'CC',
    numeroDocumento: '1032457712',
    nombres: 'Juan David',
    apellidos: 'Lasso',
    edad: 50,
    sexo: 'M',
    ciudad: 'Popayan',
    eps: 'Sanitas',
    sede: 'Popayan',
    diagnostico: 'L40.0 Psoriasis con terapia biologica',
    estado: 'Seguimiento',
    contratoId: 'ctr-002',
    programa: 'Dermatologia',
    costoAcumulado: '$11,2 M',
  },
]

export const contracts = [
  {
    id: 'ctr-001',
    eps: 'Nueva EPS',
    codigo: 'PGP-NUE-2026-01',
    nombre: 'PGP Cronicos Sur Occidente',
    modalidad: 'PGP',
    valorContrato: '$2.480 M',
    consumoActual: '$2.214 M',
    proyeccionCierre: '$2.658 M',
    margenEstimado: '9,2%',
    riesgo: 'Rojo',
    poblacion: 4620,
    desviacion: '+7,2%',
  },
  {
    id: 'ctr-002',
    eps: 'Sanitas',
    codigo: 'PGP-SAN-2026-03',
    nombre: 'PGP Dermatologia Integral',
    modalidad: 'PGP',
    valorContrato: '$1.120 M',
    consumoActual: '$894 M',
    proyeccionCierre: '$1.018 M',
    margenEstimado: '14,1%',
    riesgo: 'Amarillo',
    poblacion: 1980,
    desviacion: '+2,1%',
  },
]

export const ruleCatalog = [
  {
    id: 'follow-up-gap',
    name: 'Paciente sin control reciente',
    description: 'Detecta pacientes con brecha relevante desde su ultimo control clinico.',
    category: 'clinical',
    appliesTo: ['patient', 'history'],
    condition: { metric: 'daysSinceLastControl', operator: '>', threshold: 30 },
    weight: 14,
    severity: 'alta',
    enabled: true,
    relatedModule: 'historia-clinica',
    recommendedAction: 'Programar control prioritario y verificar continuidad asistencial.',
  },
  {
    id: 'pgp-margin-at-risk',
    name: 'Contrato PGP con margen en riesgo',
    description: 'Marca casos donde el contrato asociado muestra presion de margen o desvio de consumo.',
    category: 'pgp',
    appliesTo: ['patient', 'contract'],
    condition: { metric: 'pgpMarginAtRisk', operator: '==', threshold: true },
    weight: 18,
    severity: 'critica',
    enabled: true,
    relatedModule: 'contratos-pgp',
    recommendedAction: 'Escalar el caso a seguimiento clinico-financiero.',
  },
  {
    id: 'high-cost-medication',
    name: 'Medicamento de alto costo',
    description: 'Identifica terapias con alto impacto farmacoeconomico.',
    category: 'medication',
    appliesTo: ['patient', 'medications'],
    condition: { metric: 'hasHighCostMedication', operator: '==', threshold: true },
    weight: 12,
    severity: 'alta',
    enabled: true,
    relatedModule: 'medicamentos',
    recommendedAction: 'Correlacionar respuesta clinica e impacto contractual.',
  },
]

export const clinicalContexts = {
  'pac-001': {
    diagnoses: ['M06.9 Artritis reumatoide seropositiva'],
    medications: [{ id: 'med-001', nombre: 'Adalimumab 40 mg', estado: 'Activo', tipoCosto: 'Alto costo' }],
    history: {
      lastControlDate: '2026-06-10',
      completenessRatio: 0.9,
      adherenceRisk: false,
      highRiskDiagnosis: true,
    },
    consumptions: {
      accumulatedCost: '$18,6 M',
      monthlyCost: '$4,2 M',
      expectedMonthlyCost: '$2,4 M',
      potentialAvoidableEvent: true,
    },
  },
  'pac-002': {
    diagnoses: ['L40.0 Psoriasis vulgar severa'],
    medications: [{ id: 'med-002', nombre: 'Secukinumab 150 mg', estado: 'Activo', tipoCosto: 'Alto costo' }],
    history: {
      lastControlDate: '2026-06-08',
      completenessRatio: 0.85,
      adherenceRisk: true,
      highRiskDiagnosis: false,
    },
    consumptions: {
      accumulatedCost: '$11,2 M',
      monthlyCost: '$3,5 M',
      expectedMonthlyCost: '$2,1 M',
      potentialAvoidableEvent: false,
    },
  },
}
